// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1CIkOeSKbfCrEzquyr9CsBDvyIVeFBs',
    appId: '1:919702107545:web:47eb7307c4c8be4dce8f08',
    messagingSenderId: '919702107545',
    projectId: 'poultry-assistant-de583',
    authDomain: 'poultry-assistant-de583.firebaseapp.com',
    storageBucket: 'poultry-assistant-de583.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxSY89iTiOzB_b4fYSzheJv5GWkOeNwrQ',
    appId: '1:919702107545:android:f594154c7c9f7487ce8f08',
    messagingSenderId: '919702107545',
    projectId: 'poultry-assistant-de583',
    storageBucket: 'poultry-assistant-de583.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKIfYmW-kLYPvFysUiMuOY8HRLgLbE0Xk',
    appId: '1:919702107545:ios:2a42825ed1df791ace8f08',
    messagingSenderId: '919702107545',
    projectId: 'poultry-assistant-de583',
    storageBucket: 'poultry-assistant-de583.appspot.com',
    iosClientId: '919702107545-qi8masq4n91kubajhgb076e48tl3lui7.apps.googleusercontent.com',
    iosBundleId: 'com.example.poultryAssistant',
  );
}
